services:
  go:
    build:
      context: .
      target: final
    environment:
      - APP_CONTAINER_PORT=${APP_CONTAINER_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE}
    volumes:
      - .:/app
    ports:
      - "${APP_LOCAL_PORT}:${APP_CONTAINER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", $POSTGRES_USER]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pg-data:
